- hosts: production

  tasks:
    - name: check ssh connection
      ansible.builtin.ping:

    - name: clean local repo
      ansible.builtin.shell: |
        git reset --hard
        git clean -fd
      args:
        chdir: "{{ project_path }}"
        executable: /bin/bash


    - name: retrieve last version of repository
      ansible.builtin.git:
        repo: "git@github.com:maugme/patience.git"
        dest: "{{ project_path }}"
        version: prod
        force: yes
        update: yes

    - name: activate python environment and install dependencies
      ansible.builtin.shell: |
        source ~/.profile
        uv sync
        source .venv/bin/activate
        uv run manage.py migrate
        uv run manage.py collectstatic --no-input
      args:
        chdir: "{{ project_path }}"
        executable: /bin/bash

    - name: restart gunicorn
      become: true
      ansible.builtin.systemd_service:
        name: gunicorn_patience
        state: restarted
        daemon_reload: yes